(0.000) SELECT "alumnos_alumno"."rut", "alumnos_alumno"."nombre", "alumnos_alumno"."apellido_paterno", "alumnos_alumno"."apellido_materno", "alumnos_alumno"."fecha_nacimiento", "alumnos_alumno"."idGenero", "alumnos_alumno"."telefono", "alumnos_alumno"."email", "alumnos_alumno"."direccion", "alumnos_alumno"."activo" FROM "alumnos_alumno" ORDER BY "alumnos_alumno"."apellido_paterno" ASC LIMIT 21; args=(); alias=default
Exception while resolving variable 'mensaje' in template 'alumnos/alumnos_list.html'.
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\django\template\base.py", line 875, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "C:\Python312\Lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'mensaje'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\django\template\base.py", line 881, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
                                            ^^^^^^^^
AttributeError: type object 'RequestContext' has no attribute 'mensaje'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'mensaje'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\django\template\base.py", line 898, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [mensaje] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x000002B158107A60>>, 'request': <WSGIRequest: GET '/alumnos/crud'>, 'user': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x000002B15821E1E0>>, 'perms': PermWrapper(<SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x000002B15821E1E0>>), 'messages': <FallbackStorage: request=<WSGIRequest: GET '/alumnos/crud'>>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'alumnos': <QuerySet [<Alumno:   >, <Alumno: Salvador Allende Gossens>, <Alumno: Jimena Estuardo Uribe>, <Alumno: Vicente Fredes Estuardo>, <Alumno: Rodrigo Fredes Veas>, <Alumno: Gonzalo Muga Escobar>, <Alumno: Caroline Polachek Lisa>, <Alumno: Natalia Pérez Peralta>, <Alumno: Nicolás Stuardo Huerta>, <Alumno: Avril Vandella Lavigne>]>}, {'block': <Block Node: content. Contents: [<TextNode: '\n    <header>\n      <div '>, <django.template.defaulttags.CommentNode object at 0x000002B1581E9FA0>, <TextNode: '\n        <div class="col-'>, <URLNode view_name=''alumnosAdd'' args=[] kwargs={} as=None>, <TextNode: '">Agregar Alumno</a>\n    '>, <IfNode>, <TextNode: '\n    </div>\n\n    <div cla'>, <IfNode>, <TextNode: '    \n        </table>\n   '>]>}]
(0.000) SELECT "alumnos_alumno"."rut", "alumnos_alumno"."nombre", "alumnos_alumno"."apellido_paterno", "alumnos_alumno"."apellido_materno", "alumnos_alumno"."fecha_nacimiento", "alumnos_alumno"."idGenero", "alumnos_alumno"."telefono", "alumnos_alumno"."email", "alumnos_alumno"."direccion", "alumnos_alumno"."activo" FROM "alumnos_alumno" ORDER BY "alumnos_alumno"."apellido_paterno" ASC; args=(); alias=default
(0.000) SELECT "alumnos_genero"."idGenero", "alumnos_genero"."genero" FROM "alumnos_genero" WHERE "alumnos_genero"."idGenero" = 1 LIMIT 21; args=(1,); alias=default
(0.000) SELECT "alumnos_genero"."idGenero", "alumnos_genero"."genero" FROM "alumnos_genero" WHERE "alumnos_genero"."idGenero" = 2 LIMIT 21; args=(2,); alias=default
(0.000) SELECT "alumnos_genero"."idGenero", "alumnos_genero"."genero" FROM "alumnos_genero" WHERE "alumnos_genero"."idGenero" = 1 LIMIT 21; args=(1,); alias=default
(0.000) SELECT "alumnos_genero"."idGenero", "alumnos_genero"."genero" FROM "alumnos_genero" WHERE "alumnos_genero"."idGenero" = 1 LIMIT 21; args=(1,); alias=default
(0.000) SELECT "alumnos_genero"."idGenero", "alumnos_genero"."genero" FROM "alumnos_genero" WHERE "alumnos_genero"."idGenero" = 1 LIMIT 21; args=(1,); alias=default
(0.000) SELECT "alumnos_genero"."idGenero", "alumnos_genero"."genero" FROM "alumnos_genero" WHERE "alumnos_genero"."idGenero" = 2 LIMIT 21; args=(2,); alias=default
(0.000) SELECT "alumnos_genero"."idGenero", "alumnos_genero"."genero" FROM "alumnos_genero" WHERE "alumnos_genero"."idGenero" = 2 LIMIT 21; args=(2,); alias=default
(0.000) SELECT "alumnos_genero"."idGenero", "alumnos_genero"."genero" FROM "alumnos_genero" WHERE "alumnos_genero"."idGenero" = 1 LIMIT 21; args=(1,); alias=default
(0.000) SELECT "alumnos_genero"."idGenero", "alumnos_genero"."genero" FROM "alumnos_genero" WHERE "alumnos_genero"."idGenero" = 2 LIMIT 21; args=(2,); alias=default
Exception while resolving variable 'current_year' in template 'alumnos/alumnos_list.html'.
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\django\template\base.py", line 875, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "C:\Python312\Lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'current_year'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\django\template\base.py", line 881, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
                                            ^^^^^^^^
AttributeError: type object 'RequestContext' has no attribute 'current_year'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'current_year'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\django\template\base.py", line 898, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [current_year] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x000002B158107A60>>, 'request': <WSGIRequest: GET '/alumnos/crud'>, 'user': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x000002B15821E1E0>>, 'perms': PermWrapper(<SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x000002B15821E1E0>>), 'messages': <FallbackStorage: request=<WSGIRequest: GET '/alumnos/crud'>>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'alumnos': <QuerySet [<Alumno:   >, <Alumno: Salvador Allende Gossens>, <Alumno: Jimena Estuardo Uribe>, <Alumno: Vicente Fredes Estuardo>, <Alumno: Rodrigo Fredes Veas>, <Alumno: Gonzalo Muga Escobar>, <Alumno: Caroline Polachek Lisa>, <Alumno: Natalia Pérez Peralta>, <Alumno: Nicolás Stuardo Huerta>, <Alumno: Avril Vandella Lavigne>]>}]
"GET /alumnos/crud HTTP/1.1" 200 11721
"GET /static/css/styles.css HTTP/1.1" 304 0
